# Generated by Django 5.2.4 on 2025-08-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programa",
            name="codigo",
            field=models.IntegerField(unique=True, verbose_name="Código del Programa"),
        ),
    ]
