# Generated by Django 5.2.4 on 2025-08-15 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aprendices", "0002_alter_aprendiz_options_remove_aprendiz_programa_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_equipo",
                    models.CharField(
                        choices=[
                            ("Portátil", "Portátil"),
                            ("Escritorio", "Escritorio"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "procedencia",
                    models.CharField(
                        choices=[("Propio", "Propio"), ("SENA", "SENA")], max_length=20
                    ),
                ),
                (
                    "condicion_uso",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Prestado", "Prestado"),
                            ("Uso interno", "Uso interno"),
                        ],
                        help_text="Solo aplica si el equipo es del SENA",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("marca", models.CharField(max_length=50)),
                ("modelo", models.CharField(max_length=50)),
                (
                    "numero_serie",
                    models.CharField(max_length=50, null=True, unique=True),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "aprendiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipos",
                        to="aprendices.aprendiz",
                    ),
                ),
            ],
        ),
    ]
